# Generated by Django 3.2 on 2021-11-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='ctualização')),
                ('status', models.BooleanField(default=True, verbose_name='ctatus')),
                ('titulo', models.CharField(help_text='Máximo 40 caracteres', max_length=40, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='ctualização')),
                ('tarefa_texto', models.CharField(help_text='Máximo 50 caracteres', max_length=50, verbose_name='tarefa')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('lista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lista')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
